// <auto-generated />
using System;
using BancoDados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210630150915_Tarefas")]
    partial class Tarefas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Dominio.tblTarefa", b =>
                {
                    b.Property<int>("intTarefaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("bitCompleto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dteCadastro")
                        .HasColumnType("TEXT");

                    b.Property<int>("intUsuarioID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tblUsuariointUsuarioID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("txtDescricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("txtTitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("intTarefaID");

                    b.HasIndex("tblUsuariointUsuarioID");

                    b.ToTable("TastblTarefak");
                });

            modelBuilder.Entity("Dominio.tblUsuario", b =>
                {
                    b.Property<int>("intUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("txtNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("intUsuarioID");

                    b.ToTable("tblUsuario");
                });

            modelBuilder.Entity("Dominio.tblTarefa", b =>
                {
                    b.HasOne("Dominio.tblUsuario", "tblUsuario")
                        .WithMany("txtTarefa")
                        .HasForeignKey("tblUsuariointUsuarioID");

                    b.Navigation("tblUsuario");
                });

            modelBuilder.Entity("Dominio.tblUsuario", b =>
                {
                    b.Navigation("txtTarefa");
                });
#pragma warning restore 612, 618
        }
    }
}
